<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Lav-Gupta.domain.name" failures="1" tests="2" name="Default test" time="171.265" errors="0" timestamp="19 Aug 2020 18:22:41 GMT">
  <testcase classname="com.qa.testcases.AppiumDemo" name="loginIntoApplicationViaEmail" time="14.802"/>
  <testcase classname="com.qa.testcases.AppiumDemo" name="VerifyDesiredProductDetailsOnCheckoutPage" time="136.114">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Desired Product Name Not Mached With Excepted Result expected [Ameriwood] but found [Ameriwood Home]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Desired Product Name Not Mached With Excepted Result expected [Ameriwood] but found [Ameriwood Home]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.qa.pages.LoginPage.verifyProductDetails(LoginPage.java:200)
	at com.qa.testcases.AppiumDemo.VerifyDesiredProductDetailsOnCheckoutPage(AppiumDemo.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyDesiredProductDetailsOnCheckoutPage -->
</testsuite> <!-- Default test -->
